---
title: "R Notebook"
output: html_notebook
---

```{r}
library("RColorBrewer")
library(ggplot2)
library(tidyverse)
```

```{r}
n=6
nn = rnorm(n)/sqrt(n)
nn
cumsum(nn)
```



```{r}
set.seed(20174558)
Brownian<-function(paths=10,n=5000,  drift=0,  diffusion=1) 
{
  times <- seq(0, 1, length.out=n)
  X<-matrix(0,nrow=(n),ncol=paths)
	maximum <- matrix(0, nrow=1, ncol = paths)
	means <- matrix(0, nrow=1, ncol = paths)	
  for(i in 1:paths)
    {
    dW <- rnorm(n)/sqrt(n)
    W <- cumsum(dW)
    X[,i] <- drift*times + diffusion*cumsum(dW)
    maximum[1,i]<-max(X[,i])
    means[1,i] <- mean(X[n,i])
  
  par(mfrow = c(2,1))
  hist(diff(X[,i]))
  qqnorm(diff(X[,i]))
  qqline(diff(X[,i]))
  print(mean(X[,i]))
  print(sd(X[,i]))
  print(var(X[,i]))
  print(means)
  }

matplot(X,main="Brownian Motion",xlab="Time",ylab="Path",type="l")
	        #col=brewer.pal(n = paths, name = "Spectral"),
	        # x = seq(0, 1, length.out = n))

}
Brownian(paths=5,n=50000,  drift=10,  diffusion=1)


# par(mfrow=c(1,2))
#	matplot(brown,main="Brownian Motion",xlab="Time",ylab="Path",type="l")
	        #col=brewer.pal(n = paths, name = "Spectral"),
	        # x = seq(0, 1, length.out = n))


#brown <- Brownian(paths=10,n=2000,  drift=5,  diffusion=1)

#data.frame(price = brown[i, ]) %>%
# ggplot(aes(x = price)) +
 # geom_histogram(aes(y = ..density..), binwidth = 0.1) +
 #   geom_density() + 
 #   ggtitle('terminal price distribution')

```


```{r}
set.seed(20174558)
BrownianBridge<-function() # Standard Browninan with drift 0.25 and diffusion 0.5
{
  paths<-10
  n <- 5000
  times <- seq(0, 1, length.out=n)
  drift <- 0.5
  diffusion <- 0.2
  XB<-matrix(0,nrow=(n),ncol=paths)
	maximum <- matrix(0, nrow=1, ncol = paths)
  for(i in 1:paths)
    {
    dW <- rnorm(n)/sqrt(n)
    W <- cumsum(dW)
    X <- drift*times + diffusion*cumsum(dW)
    XB[,i] <- X - (times) * X[n] # X - (times/5000) * X[n]*(times/5000)/(1-times/5000) goes back to brownian motion
#    dX[,i] <- drift*times + diffusion*cumsum(dW)
    maximum[1,i]<-max(XB[,i])
  }
#	par(mfrow=c(1,2))
	matplot(XB,main="Brownian Bridge",xlab="Time",ylab="Path",type="l",
	#        col=brewer.pal(n = paths, name = "Spectral"), 
	        x = seq(0, 1, length.out = 5000))
#	abline(h=mean(maximum), col = "black",)
#	matplot(XB,main="Brownian Bridge",xlab="Time",ylab="Path",type="l",col=brewer.pal(n = paths, name = "Spectral"))
#	legend("bottomleft",legend=cat("drift = ", drift),cat("diffusion = ", diffusion)) 
#	abline(v=4000)
#	abline(h=maximum,col=brewer.pal(n = paths, name = "Spectral"))
#	print(maximum)
#	print(mean(maximum))
  }


BrownianBridge()

```


```{r}
set.seed(20174558)
GeometricBrownian<-function() # Standard Browninan with drift 0.25 and diffusion 0.5
{
  paths<-30
  n <- 5000
  times <- seq(0, 1, length.out=n)
  drift <- 0.7
  diffusion <- 0.5
  X<-matrix(0,nrow=(n),ncol=paths)
	maximum <- matrix(0, nrow=1, ncol = paths)
  for(i in 1:paths)
    {
    dW <- rnorm(n)/sqrt(n)
    W <- cumsum(dW)
    mu <- drift - 0.5* diffusion^2
    X[,i] <- exp((drift - 0.5*(diffusion)^2)*times + diffusion*cumsum(dW))
    maximum[1,i]<-max(X[,i])
  #  print(mean(X))
 #   print(mean(exp(0.7*times)))
  }
#	par(mfrow=c(1,2))
	matplot(X,main="Geometric Brownian Motion",xlab="Time",ylab="Path",type="l",col=brewer.pal(n = paths, name = "Spectral"))
	abline(h=mean(maximum), col = "black",)
	matplot(X,main="Geometric Brownian Motion",xlab="Time",ylab="Path",type="l",col=brewer.pal(n = paths, name = "Spectral"))
	abline(v=4000)
	abline(h=maximum,col=brewer.pal(n = paths, name = "Spectral"))
#	print(maximum)
#	print(mean(maximum))
#	print(mean(X))
#	print(mean(exp(drift*times)))
}


GeometricBrownian()

```