---
title: "R Notebook"
output: html_notebook
---


```{r}
runs = 100000
sim = rnorm(runs,mean=1,sd=10)
monte.int = sum(sim >= 4 & sim <= 7)/runs
monte.int
```

Approximating Pi through Monte Carlo
```{r}
runs <- 100000
#runif samples from a uniform distribution
xs <- runif(runs,min=-1,max=1)
ys <- runif(runs,min=-1,max=1)
in.circle <- xs^2 + ys^2 <= 1^2
mc.pi <- (sum(in.circle)/runs)*4
plot(xs,ys,pch='.',col=ifelse(in.circle,"blue","grey")
     ,xlab='',ylab='',asp=1,
     main=paste("MC Approximation of Pi =",mc.pi))
```

Probability of a spinner
```{r}
runs <- 100000
#simulates on game of 10 spins, returns whether the sum of all the spins is < 0
play.game <- function(){
  results <- sample(c(1,1,-1,2),10,replace=T)
  return(sum(results) < 0)
}
mc.prob <- sum(replicate(runs,play.game()))/runs
mc.prob
```


Predicting the stock market
```{r}
days <- 200
changes <- rnorm(200,mean=1.0001,sd=0.005)
plot(cumprod(c(30,changes)),type='l',ylab="Price",xlab="day",main="Sample Closing Price")
```

```{r}
runs <- 100000
#simulates future movements and returns the closing price on day 200
generate.path <- function(){
  days <- 200
  changes <- rnorm(200,mean=1.0001,sd=0.005)
  sample.path <- cumprod(c(30,changes))
  closing.price <- sample.path[days+1] #+1 adding opening price
  return(closing.price)
}

mc.closing <- replicate(runs,generate.path())
hist(mc.closing, xlab="Price",main="Histogram of Closing Price")
```



