---
title: "R Notebook"
output: html_notebook
---
```{r}
library(astsa)
```

```{r}
plot(X)
```

```{r}
Brownian<-function() # Standard Browninan with drift 0.25 and diffusion 0.5
{
  paths<-1
  n <- 5000
  times <- seq(0, 1, length.out=n)
  drift <- 0.15
  diffusion <- 0.2
  X<-matrix(0,nrow=(n),ncol=paths)
	maximum <- matrix(0, nrow=1, ncol = paths)
	means <- matrix(0, nrow=1, ncol = paths)	
  for(i in 1:paths)
    {
    dW <- rnorm(n)/sqrt(n)
    W <- cumsum(dW)
    X[,i] <- drift*times + diffusion*cumsum(dW)
    maximum[1,i]<-max(X[,i])
    means[1,i] <- mean(X[n,i])
  }

	matplot(X,main="Brownian Motion",xlab="Time",ylab="Path",type="l",col=brewer.pal(n = paths, name = "Spectral"),
	         x = seq(0, 1, length.out = 5000))
	abline(h=mean(maximum), col = "black",)
	matplot(X,main="Brownian Motion",xlab="Time",ylab="Path",type="l",col=brewer.pal(n = paths, name = "Spectral"))
	abline(v=4000)
	abline(h=maximum,col=brewer.pal(n = paths, name = "Spectral"))
	
  trend = time(X) - mean(time(X)) # center time
  const = time(X)/time(X) # appropriate time series of 1s
  tempr
  plot(tempr)
  plot(cmort)
  cmo
  par
 # ded = ts.intersect(M=X, T1=lag(tempr,-1), P=part, P4=lag(part,-4),
 # trend, const)

}
  Brownian()
```


